---
title: 'STAT 140: Homework 1'
author: "YOUR NAME HERE"
date: 'Due Date: Friday, 1/31/2020'
output: pdf_document
---

## BOOK EXERCISES (OpenIntro Statistics, Fourth Edition)

### Section 1.2

1.3) **Air pollution and birth outcomes, study components.** Researchers collected data to examine the relationship between air pollutants and preterm births in Southern California. During the study air pollution levels were measured by air quality monitoring stations. Specifically, levels of carbon monoxide (CO) were recorded in parts per million, nitrogen dioxide and ozone in parts per hundred million, and coarse particulate matter (PM$_{10}$) in $\mu$g/m$^3$. Length of gestation data were collected on 143,196 births between the years 1989 and 1993, and air pollution exposure during gestation was collected for each birth. The analysis suggested that increased ambient PM$_{10}$ and, to a lesser degree, CO concentrations may be associated with the occurrence of preterm births.

a) Identify the main research question of the study.

**Answer:**

b) Who are the subjects in this study, and how many are included?

**Answer:**

c) What are the variables in the study? Identify each variable as numerical or categorical. If numerical, state whether the variable is discrete or continuous. If categorical, state whether the variable is ordinal.

**Answer:**

1.8) **Sinusitis and antibiotics, Part II.** Exercise 1.2 introduced a study exploring the effect of antibiotic treatment for acute sinusitis. Study participants received either a 10-day course of an antibiotic (treatment) or a placebo similar in appearance and taste (control). At the end of the 10-day period, patients were asked if they experienced improvement in symptoms. What are the explanatory and response variables in this study?

**Answer:**

1.9) **Fisher's irises.** Sir Ronald Aylmer Fisher was an English statistician, evolutionary biologist, and geneticist who worked on a data set that contained sepal length and width, and petal length and width from three species of iris flowers (*setosa*, *versicolor*, and *virginica*). There were 50 flowers from each species in the data set.

a) How many cases were included in the data?

**Answer:**

b) How many numerical variables are included in the data? Indicate what they are, and if they are continuous or discrete.

**Answer:**

c) How many categorical variables are included in the data, and what are they? List the corresponding levels (categories).

**Answer:**

### Section 1.3

1.17) **Relaxing after work.** The General Social Survey asked the question, "After an average work day, about how many hours do you have to relax or pursue activities that you enjoy?" to a random sample of 1,155 Americans. The average relaxing time was found to be 1.65 hours. Determine which of the following is an observation, a variable, a sample statistic (value calculated based on the observed sample), or a population parameter.

a) An American in the sample.

**Answer:**

b) Number of hours spent relaxing after an average work day.

**Answer:**

c) 1.65

**Answer:**

d) Average number of hours all Americans spend relaxing after an average work day.

**Answer:**

1.22) **Stressed out, Part I.** A study that surveyed a random sample of otherwise healthy high school students found that they are more likely to get muscle cramps when they are stressed. The study also noted that students drink more coffee and sleep less when they are stressed.

a) What type of study is this?

**Answer:**

b) Can this study be used to conclude a causal relationship between increased stress and muscle cramps?

**Answer:**

c) State possible confounding variables that might explain the observed relationship between increased stress and muscle cramps.

**Answer:**

1.27) **Sampling strategies.** A statistics student who is curious about the relationship between the amount of time students spend on social networking sites and their performance at school decides to conduct a survey. Various research strategies for collecting data are described below. In each, name the sampling method proposed and any bias you might expect.

a) He randomly samples 40 students from the study's population, gives them the survey, asks them to fill it out and bring it back the next day.

**Answer:**

b) He gives out the survey only to his friends, making sure each of them fills out the survey.

**Answer:**

c) He posts a link to an online survey on Facebook and asks his friends to fill out the survey.

**Answer:**

d) He randomly samples 5 classes and asks a random sample of students from those classes to fill out the survey.

**Answer:**

### Section 1.4

1.32) **Music and learning.** You would like to conduct an experiment in class to see if students learn better if they study without any music, with music that has no lyrics (instrumental), or with music that has lyrics. Briefly outline a design for this study.

**Answer:**

1.37) **Chia seeds and weight loss.** Chia Pets - those terra-cotta figurines that sprout fuzzy green hair - made the chia plant a household name. But chia has gained an entirely new reputation as a diet supplement. In one 2009 study, a team of researchers recruited 38 men and divided them randomly into two groups: treatment or control. They also recruited 38 women, and they randomly placed half of these participants into the treatment group and the other half into the control group. One group was given 25 grams of chia seeds twice a day, and the other was given a placebo. The subjects volunteered to be a part of the study. After 12 weeks, the scientists found no significant difference between the groups in appetite or weight loss.

a) What type of study is this?

**Answer:**

b) What are the experimental and control treatments in this study?

**Answer:**

c) Has blocking been used in this study? If so, what is the blocking variable?

**Answer:**

d) Has blinding been used in this study?

**Answer:**

e) Comment on whether or not we can make a causal statement, and indicate whether or not we can generalize the conclusion to the population at large.

**Answer:**

1.40) **Income and education in US counties.** The scatterplot in your textbook shows the relationship between per capita income (in thousands of dollars) and percent of population with a bachelor's degree in 3,143 counties in the US in 2010. 

a) What are the explanatory and response variables?

**Answer:**

b) Describe the relationship between the two variables. Make sure to discuss unusual observations, if any.

**Answer:**

c) Can we conclude that having a bachelor's degree increases one's income?

**Answer:**
